export const FORM_TEMPLATES = [
  {id:'contact',name:'Contact & enquiry',category:'Business',icon:'💬',description:'General enquiries, customer messages and website contact forms.',tags:['contact','enquiry','business'],fields:[['name','Full name','text',true],['email','Email address','email',true],['phone','Phone number','tel',false],['subject','Subject','text',false],['message','Message','textarea',true]]},
  {id:'lead-capture',name:'Lead capture',category:'Sales & Marketing',icon:'🎯',description:'Capture prospects from landing pages, campaigns and ads.',tags:['lead','sales','marketing'],fields:[['name','Full name','text',true],['email','Work email','email',true],['company','Company','text',false],['phone','Phone number','tel',false],['interest','What are you interested in?','select',true,['Product demo','Pricing','Partnership','Other']]]},
  {id:'quote-request',name:'Quote request',category:'Sales & Marketing',icon:'🧾',description:'Collect the information needed to prepare a quote or estimate.',tags:['quote','estimate','sales'],fields:[['name','Full name','text',true],['email','Email address','email',true],['phone','Phone number','tel',false],['service','Service needed','text',true],['budget','Estimated budget','text',false],['details','Project details','textarea',true]]},
  {id:'support',name:'Support ticket',category:'Customer service',icon:'🛠️',description:'Collect structured customer support requests and issue details.',tags:['support','helpdesk','ticket'],fields:[['name','Name','text',true],['email','Email address','email',true],['order_id','Order / account ID','text',false],['priority','Priority','select',true,['Low','Normal','High','Urgent']],['message','Describe the issue','textarea',true],['attachment','Screenshot or file','file',false]]},
  {id:'feedback',name:'Customer feedback',category:'Customer service',icon:'⭐',description:'Collect ratings, suggestions and customer experience feedback.',tags:['feedback','review','rating'],fields:[['name','Name','text',false],['email','Email address','email',false],['rating','Overall rating','select',true,['1 - Very poor','2 - Poor','3 - Okay','4 - Good','5 - Excellent']],['category','Feedback type','select',true,['Product','Service','Website','Support','Other']],['message','Tell us more','textarea',true]]},
  {id:'appointment',name:'Appointment request',category:'Appointments & bookings',icon:'📅',description:'Let clients request a date, service and preferred time.',tags:['appointment','booking','schedule'],fields:[['name','Full name','text',true],['email','Email address','email',true],['phone','Phone number','tel',true],['service','Service','text',true],['preferred_date','Preferred date','date',true],['preferred_time','Preferred time','time',false],['notes','Notes','textarea',false]]},
  {id:'booking',name:'Booking / reservation',category:'Appointments & bookings',icon:'🗓️',description:'Collect reservation details for venues, restaurants, tours and services.',tags:['booking','reservation','event'],fields:[['name','Name','text',true],['email','Email address','email',true],['phone','Phone number','tel',false],['date','Date','date',true],['guests','Number of guests','number',true],['special_requests','Special requests','textarea',false]]},
  {id:'event',name:'Event registration',category:'Events & communities',icon:'🎟️',description:'Register attendees and collect event preferences.',tags:['event','registration','attendee'],fields:[['name','Full name','text',true],['email','Email address','email',true],['phone','Phone number','tel',false],['ticket_type','Ticket type','select',true,['General','VIP','Student','Other']],['company','Company / organisation','text',false],['notes','Notes','textarea',false]]},
  {id:'job-application',name:'Job application',category:'HR & hiring',icon:'💼',description:'Collect candidate information, experience and a CV upload.',tags:['job','career','hiring','cv'],fields:[['name','Full name','text',true],['email','Email address','email',true],['phone','Phone number','tel',true],['role','Role applied for','text',true],['experience','Years of experience','number',false],['cover_letter','Cover letter','textarea',true],['cv','CV / resume','file',true]]},
  {id:'leave-request',name:'Leave request',category:'HR & internal',icon:'🏖️',description:'Simple employee leave request workflow for internal teams.',tags:['leave','hr','employee'],fields:[['name','Employee name','text',true],['email','Work email','email',true],['leave_type','Leave type','select',true,['Annual','Sick','Parental','Emergency','Other']],['start_date','Start date','date',true],['end_date','End date','date',true],['reason','Reason / notes','textarea',false]]},
  {id:'project-brief',name:'Project brief',category:'Professional services',icon:'🧠',description:'Help freelancers, agencies and consultants qualify new projects.',tags:['project','agency','freelancer','brief'],fields:[['name','Your name','text',true],['email','Email address','email',true],['company','Company','text',false],['project_type','Project type','text',true],['budget','Budget range','text',false],['deadline','Target deadline','date',false],['brief','Tell us about the project','textarea',true],['reference_files','Reference files','file',false]]},
  {id:'client-intake',name:'Client intake',category:'Professional services',icon:'📋',description:'Collect new-client details for consultants, accountants, agencies and service providers.',tags:['client','intake','consulting'],fields:[['name','Full name','text',true],['email','Email address','email',true],['phone','Phone number','tel',false],['company','Company','text',false],['service','Service required','text',true],['goals','Goals / requirements','textarea',true],['documents','Supporting documents','file',false]]},
  {id:'real-estate',name:'Property enquiry',category:'Real estate',icon:'🏠',description:'Capture buyer, renter or property-service enquiries.',tags:['real estate','property','rent','housing'],fields:[['name','Full name','text',true],['email','Email address','email',true],['phone','Phone number','tel',false],['property','Property / listing','text',true],['budget','Budget','text',false],['move_date','Preferred move date','date',false],['message','Message','textarea',true]]},
  {id:'school-admission',name:'School admission enquiry',category:'Education',icon:'🎓',description:'Collect prospective student or parent enquiries without requiring a custom backend.',tags:['school','education','admission'],fields:[['parent_name','Parent / guardian name','text',true],['email','Email address','email',true],['phone','Phone number','tel',true],['student_name','Student name','text',true],['class','Class / programme','text',true],['message','Enquiry','textarea',false]]},
  {id:'vendor',name:'Vendor onboarding',category:'Operations',icon:'🤝',description:'Collect supplier details and supporting documents.',tags:['vendor','supplier','onboarding'],fields:[['contact_name','Contact name','text',true],['email','Business email','email',true],['company','Company name','text',true],['phone','Phone number','tel',false],['services','Products / services','textarea',true],['documents','Company documents','file',false]]},
  {id:'maintenance',name:'Maintenance request',category:'Property & operations',icon:'🔧',description:'Collect repair and facility maintenance requests with optional photos.',tags:['maintenance','repair','facility'],fields:[['name','Requester name','text',true],['email','Email address','email',true],['location','Location / unit','text',true],['priority','Priority','select',true,['Low','Normal','High','Emergency']],['issue','Describe the issue','textarea',true],['photos','Photos / files','file',false]]},
  {id:'complaint',name:'Complaint / incident report',category:'Customer service',icon:'🚩',description:'Structured complaint intake for organisations and service teams.',tags:['complaint','incident','service'],fields:[['name','Name','text',false],['email','Email address','email',false],['reference','Reference / ticket number','text',false],['date','Date of incident','date',false],['details','What happened?','textarea',true],['evidence','Supporting files','file',false]]},
  {id:'newsletter',name:'Newsletter signup',category:'Marketing',icon:'📣',description:'Simple email capture for newsletters and audience lists.',tags:['newsletter','subscribe','email'],fields:[['email','Email address','email',true],['name','Name','text',false],['consent','I agree to receive updates','checkbox',true]]},
  {id:'blank',name:'Blank form',category:'General',icon:'✨',description:'Start from a clean endpoint and add your own fields in your website builder.',tags:['blank','custom','other'],fields:[]}
];
export const TEMPLATE_CATEGORIES=['All',...Array.from(new Set(FORM_TEMPLATES.map(t=>t.category)))];
export function templateById(id){return FORM_TEMPLATES.find(t=>t.id===id)||FORM_TEMPLATES.find(t=>t.id==='blank')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
export function fieldMarkup(t){return t.fields.map(([name,label,type,required,options])=>{const n=esc(name),l=esc(label);if(type==='textarea')return `<label>${l}<textarea name="${n}"${required?' required':''}></textarea></label>`;if(type==='select')return `<label>${l}<select name="${n}"${required?' required':''}><option value="">Select…</option>${(options||[]).map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('')}</select></label>`;if(type==='checkbox')return `<label><input type="checkbox" name="${n}" value="yes"${required?' required':''}> ${l}</label>`;if(type==='radio')return `<fieldset><legend>${l}</legend>${(options||[]).map(o=>`<label><input type="radio" name="${n}" value="${esc(o)}"${required?' required':''}> ${esc(o)}</label>`).join('')}</fieldset>`;return `<label>${l}<input type="${esc(type)}" name="${n}"${required?' required':''}></label>`}).join('\n')}
