import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Code2,Inbox,Mail,Table2,ArrowRight,Copy,Check,ShieldAlert,CopyCheck,TrendingUp,HardDrive,Activity} from 'lucide-react';
import {api,copyText} from '../lib/api';
export default function Dashboard(){
 const [data,setData]=useState({forms:[],submissions:[],summary:{total:0,spam:0,duplicates:0,sources:{},daily:{}}}),[copied,setCopied]=useState(false);
 useEffect(()=>{api('/api/form-stats').then(setData).catch(console.error)},[]);
 const snippet='<script src="https://wyform.ng/widget.js"></script>';
 const copy=async()=>{const ok=await copyText(snippet);setCopied(ok);setTimeout(()=>setCopied(false),1500)};
 return <>
  <div className="pageHead"><div><div className="eyebrow">FORM BACKEND</div><h1>The 10-second backend for any HTML form.</h1><p className="muted">One script. One attribute. Submissions land here and can be emailed from your own Gmail.</p></div><Link className="primary" to="/forms"><Code2 size={17}/> Create form</Link></div>
  <div className="stats"><div className="stat"><Code2/><b>{data.forms.length}</b><span>Forms</span></div><div className="stat"><Inbox/><b>{data.submissions.length}</b><span>Recent submissions</span></div><div className="stat"><Mail/><b>0</b><span>WyForm email cost</span></div><div className="stat"><Table2/><b>∞</b><span>Sheets-ready</span></div><div className="stat"><ShieldAlert/><b>{data.summary.spam}</b><span>Spam blocked</span></div><div className="stat"><CopyCheck/><b>{data.summary.duplicates}</b><span>Duplicates flagged</span></div></div>
  <div className="grid2"><div className="card"><div className="cardTitle"><h3>Install once</h3><button className="iconBtn" onClick={copy}>{copied?<Check size={17}/>:<Copy size={17}/>}</button></div><p className="muted">Put this before <code>&lt;/body&gt;</code> on your site.</p><pre className="codeBlock">{snippet}</pre><p className="tiny">Then add <code>data-wyform="YOUR_FORM_KEY"</code> to each form.</p></div><div className="card"><div className="cardTitle"><h3>Free infrastructure</h3><Link className="link" to="/integrations">See integrations</Link></div><div className="steps"><div className="step"><span>1</span><div><b>Your Gmail sends email</b><p>No WyForm email provider bill.</p></div></div><div className="step"><span>2</span><div><b>Your Drive stores attachments</b><p>File bytes do not pass through WyForm.</p></div></div><div className="step"><span>3</span><div><b>Your Sheets stores exports</b><p>Keep business data in tools you already use.</p></div></div></div></div></div>
  <div className="featureGrid"><span><HardDrive/>Drive attachments</span><span><Activity/>Form health</span><span><CopyCheck/>Duplicate detection</span><span><TrendingUp/>UTM attribution</span><span><Mail/>Gmail delivery</span><span><Table2/>Sheets sync</span></div>
  <div className="grid2"><div className="card"><div className="cardTitle"><h3><TrendingUp size={18}/> Traffic sources</h3></div>{Object.entries(data.summary.sources||{}).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([k,v])=><div className="submissionRow" key={k}><div><b>{k}</b><small>{v} submission{v===1?'':'s'}</small></div><span className="badge">{Math.round(v/Math.max(1,data.summary.total)*100)}%</span></div>)}{!Object.keys(data.summary.sources||{}).length&&<div className="emptyMini">UTM sources appear here after your first campaign submission.</div>}</div><div className="card"><div className="cardTitle"><h3>Recent submissions</h3><Link className="link" to="/submissions">View all</Link></div>{data.submissions.slice(0,5).map(s=><div className="submissionRow" key={s.id}><div><b>{s.email||'Anonymous'}</b><small>{new Date(s.created_at).toLocaleString()}</small></div><ArrowRight size={16}/></div>)}{!data.submissions.length&&<div className="emptyMini">Create a form and send your first test submission.</div>}</div></div>
 </>;
}
