import React,{useEffect,useMemo,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {Save,ArrowLeft,Copy,Plus,Trash2,GripVertical,Eye,Code2,Settings2,ChevronDown} from 'lucide-react';
import {api,copyText} from '../lib/api';
import {templateById} from '../lib/formTemplates';

const TYPES=[['text','Short text'],['textarea','Long text'],['email','Email'],['tel','Phone'],['number','Number'],['date','Date'],['time','Time'],['url','Website URL'],['select','Dropdown'],['radio','Single choice'],['checkbox','Checkbox'],['file','File upload'],['rating','Rating'],['currency','Amount / currency'],['hidden','Hidden field']];
const defaultField=(type='text',i=0)=>({id:`field_${Date.now()}_${i}`,name:`field_${i+1}`,label:type==='textarea'?'Message':`Field ${i+1}`,type,required:false,placeholder:'',help:'',options:type==='select'||type==='radio'?['Option 1','Option 2']:[]});
function initialFields(form){if(Array.isArray(form.fields_schema)&&form.fields_schema.length)return form.fields_schema;const t=templateById(form.template_id);return (t?.fields||[]).map((x,i)=>({id:`template_${i}_${x[0]}`,name:x[0],label:x[1],type:x[2],required:!!x[3],placeholder:'',help:'',options:Array.isArray(x[4])?x[4]:[]}));}
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function fieldHtml(f){const req=f.required?' required':'';const ph=f.placeholder?` placeholder="${esc(f.placeholder)}"`:'';const help=f.help?`<small>${esc(f.help)}</small>`:'';if(f.type==='textarea')return `  <label>${esc(f.label)}<textarea name="${esc(f.name)}"${req}${ph}></textarea>${help}</label>`;if(f.type==='select')return `  <label>${esc(f.label)}<select name="${esc(f.name)}"${req}><option value="">Select…</option>${(f.options||[]).map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('')}</select>${help}</label>`;if(f.type==='radio')return `  <fieldset><legend>${esc(f.label)}</legend>${(f.options||[]).map(o=>`    <label><input type="radio" name="${esc(f.name)}" value="${esc(o)}"${req}> ${esc(o)}</label>`).join('\n')}</fieldset>${help}`;if(f.type==='checkbox')return `  <label><input type="checkbox" name="${esc(f.name)}" value="yes"${req}> ${esc(f.label)}</label>${help}`;if(f.type==='file')return `  <label>${esc(f.label)}<input type="file" name="${esc(f.name)}"${req}></label>${help}`;if(f.type==='rating')return `  <label>${esc(f.label)}<select name="${esc(f.name)}"${req}><option value="">Choose a rating…</option>${[1,2,3,4,5].map(n=>`<option value="${n}">${n} / 5</option>`).join('')}</select>${help}</label>`;if(f.type==='currency')return `  <label>${esc(f.label)}<input type="number" step="0.01" inputmode="decimal" name="${esc(f.name)}"${req}${ph}></label>`;return `  <label>${esc(f.label)}<input type="${esc(f.type)}" name="${esc(f.name)}"${req}${ph}></label>`;}
function fullEmbed(form,fields){const title=form.builder_title?`  <h2>${esc(form.builder_title)}</h2>\n`:'';const description=form.builder_description?`  <p>${esc(form.builder_description)}</p>\n`:'';return `<form data-wyform="${form.form_key}">\n${title}${description}${fields.map(fieldHtml).join('\n')}\n  <button type="submit">Submit</button>\n  <div data-wyform-success aria-live="polite"></div>\n  <div data-wyform-error role="alert"></div>\n</form>`}

export default function FormDetail(){
 const {id}=useParams();const nav=useNavigate();const [form,setForm]=useState(null),[fields,setFields]=useState([]),[tab,setTab]=useState('builder'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState('');
 useEffect(()=>api('/api/forms').then(x=>{const f=(x.forms||[]).find(v=>v.id===id);setForm(f);if(f)setFields(initialFields(f));}).catch(e=>setMsg(e.message)),[id]);
 const update=(k,v)=>setForm(x=>({...x,[k]:v}));
 const updateField=(idx,k,v)=>setFields(xs=>xs.map((f,i)=>i===idx?{...f,[k]:v}:f));
 const addField=()=>setFields(xs=>[...xs,defaultField('text',xs.length)]);
 const removeField=i=>setFields(xs=>xs.filter((_,n)=>n!==i));
 const move=(i,d)=>setFields(xs=>{const j=i+d;if(j<0||j>=xs.length)return xs;const a=[...xs];[a[i],a[j]]=[a[j],a[i]];return a});
 const generated=useMemo(()=>fullEmbed(form||{form_key:'YOUR_FORM_KEY'},fields),[form,fields]);
 async function save(){setBusy(true);setMsg('');try{await api(`/api/forms?id=${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({...form,fields_schema:fields})});setMsg('Saved.');}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function copy(v,k){const ok=await copyText(v);if(ok){setCopied(k);setTimeout(()=>setCopied(''),1500)}else setMsg('Copy failed. Please copy the code manually.')} 
 if(!form)return <div className="card empty">Loading form…</div>;
 return <>
  <div className="pageHead"><div><button className="ghost" onClick={()=>nav('/forms')}><ArrowLeft size={16}/> Forms</button><h1>{form.name}</h1><p className="muted">Build the form visually, then copy one production-ready embed.</p></div><button className="primary" onClick={save} disabled={busy}><Save size={16}/>{busy?'Saving…':'Save changes'}</button></div>
  <div className="builderTabs"><button className={tab==='builder'?'builderTab active':'builderTab'} onClick={()=>setTab('builder')}><Settings2 size={15}/> Builder</button><button className={tab==='preview'?'builderTab active':'builderTab'} onClick={()=>setTab('preview')}><Eye size={15}/> Preview</button><button className={tab==='code'?'builderTab active':'builderTab'} onClick={()=>setTab('code')}><Code2 size={15}/> Embed code</button></div>
  {tab==='builder'&&<>
   <div className="builderLayout"><div>
    <div className="card"><div className="cardTitle"><div><h3>Form fields</h3><p className="tiny">Add, remove and reorder fields for any profession or workflow.</p></div><button className="secondary" onClick={addField}><Plus size={15}/> Add field</button></div>
    <div className="fieldList">{fields.map((f,i)=><div className="fieldEditor" key={f.id}><div className="fieldTop"><GripVertical size={16}/><b>{f.label||'Untitled field'}</b><span className="tiny">{f.type}</span><div className="fieldMove"><button className="iconBtn" onClick={()=>move(i,-1)} title="Move up">↑</button><button className="iconBtn" onClick={()=>move(i,1)} title="Move down">↓</button><button className="iconBtn danger" onClick={()=>removeField(i)} title="Delete"><Trash2 size={14}/></button></div></div>
      <div className="fieldGrid"><label>Label<input value={f.label} onChange={e=>updateField(i,'label',e.target.value)} /></label><label>Field name<input value={f.name} onChange={e=>updateField(i,'name',e.target.value.replace(/[^a-zA-Z0-9_-]/g,'_'))}/></label><label>Type<select value={f.type} onChange={e=>updateField(i,'type',e.target.value)}>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Placeholder<input value={f.placeholder||''} onChange={e=>updateField(i,'placeholder',e.target.value)}/></label></div>
      <div className="fieldGrid"><label className="check"><input type="checkbox" checked={!!f.required} onChange={e=>updateField(i,'required',e.target.checked)}/> Required</label><label>Help text<input value={f.help||''} onChange={e=>updateField(i,'help',e.target.value)}/></label></div>
      {(f.type==='select'||f.type==='radio')&&<div className="optionEditor"><div className="cardTitle"><b>Options</b><button className="link" onClick={()=>updateField(i,'options',[...(f.options||[]),'New option'])}><Plus size={13}/> Add</button></div>{(f.options||[]).map((o,j)=><div className="optionRow" key={j}><input value={o} onChange={e=>updateField(i,'options',f.options.map((x,n)=>n===j?e.target.value:x))}/><button className="iconBtn danger" onClick={()=>updateField(i,'options',f.options.filter((_,n)=>n!==j))}><Trash2 size={13}/></button></div>)}</div>}
     </div>)}{!fields.length&&<div className="emptyMini">No fields yet. Add the first field.</div>}</div></div>
    <div className="card"><div className="cardTitle"><div><h3>Form identity</h3><p className="tiny">Optional title and description shown in your generated markup.</p></div></div><label>Title<input value={form.builder_title||''} onChange={e=>update('builder_title',e.target.value)}/></label><label>Description<textarea rows="3" value={form.builder_description||''} onChange={e=>update('builder_description',e.target.value)}/></label></div>
   </div><div><div className="card stickyCard"><div className="cardTitle"><h3>Live preview</h3><Eye size={17}/></div><div className="previewForm"><h3>{form.builder_title||form.name}</h3>{form.builder_description&&<p>{form.builder_description}</p>}{fields.map((f,i)=><div key={f.id} className="mockField"><label>{f.label}{f.required&&<span> *</span>}</label>{f.type==='textarea'?<textarea placeholder={f.placeholder}/>:f.type==='select'?<select><option>{f.placeholder||'Select…'}</option></select>:f.type==='checkbox'?<div className="mockCheck"><input type="checkbox"/> {f.label}</div>:f.type==='radio'?<div>{(f.options||[]).map(o=><span className="mockChoice" key={o}><input type="radio"/> {o}</span>)}</div>:f.type==='file'?<input type="file"/>:<input type={f.type==='currency'?'number':f.type} placeholder={f.placeholder}/>}</div>)}<button type="button" className="primary wide" onClick={()=>setMsg('Preview only — submissions are disabled here.')}>Submit</button></div></div></div></div>
  </>}
  {tab==='preview'&&<div className="card"><div className="cardTitle"><div><h3>Visitor preview</h3><p className="tiny">This is the structure visitors will receive on your site.</p></div></div><div className="previewForm previewLarge"><h2>{form.builder_title||form.name}</h2>{form.builder_description&&<p>{form.builder_description}</p>}{fields.map(f=><div className="mockField" key={f.id}><label>{f.label}{f.required&&<span> *</span>}</label>{f.type==='textarea'?<textarea placeholder={f.placeholder}/>:f.type==='select'?<select><option>{f.placeholder||'Select…'}</option>{(f.options||[]).map(o=><option key={o}>{o}</option>)}</select>:f.type==='checkbox'?<div className="mockCheck"><input type="checkbox"/> {f.label}</div>:f.type==='radio'?<div>{(f.options||[]).map(o=><span className="mockChoice" key={o}><input type="radio"/> {o}</span>)}</div>:f.type==='file'?<input type="file"/>:<input type={f.type==='currency'?'number':f.type} placeholder={f.placeholder}/>}</div>)}<button type="button" className="primary" onClick={()=>setMsg('Visitor preview only — submissions are disabled here.')}>Submit</button></div></div>}
  {tab==='code'&&<div className="card"><div className="cardTitle"><div><h3>Copy your embed</h3><p className="tiny">Paste this inside your website page. Keep the WyForm widget script installed once.</p></div><button className="primary" onClick={()=>copy(generated,'code')}>{copied==='code'?<><Copy size={15}/> Copied</>:<><Copy size={15}/> Copy full form</>}</button></div><pre className="codeBlock">{generated}</pre><div className="divider"/><h3>Endpoint attribute</h3><pre className="codeBlock">{`<form data-wyform="${form.form_key}">`}</pre><p className="tiny">The backend receives these field names automatically. File uploads use your configured Google Drive connection.</p></div>}
  <div className="card"><div className="cardTitle"><h3>Delivery & security</h3><span className="badge">Template: {form.template_category||'General'}</span></div><div className="grid2"><div><label>Email subject<input value={form.email_subject||''} onChange={e=>update('email_subject',e.target.value)}/></label><label>Success message<input value={form.success_message||''} onChange={e=>update('success_message',e.target.value)}/></label></div><div><label>Success redirect URL<input value={form.success_redirect||''} onChange={e=>update('success_redirect',e.target.value)}/></label><label className="check"><input type="checkbox" checked={form.capture_utm!==false} onChange={e=>update('capture_utm',e.target.checked)}/> Capture campaign/UTM data</label></div></div>{msg&&<p className="tiny">{msg}</p>}</div>
 </>;
}
