import React,{Suspense,lazy,useEffect,useState} from 'react';
import {Routes,Route,useLocation} from 'react-router-dom';
import {onAuthStateChanged} from './lib/firebase';
import {auth} from './lib/firebase';
import Layout from './components/Layout';
const Dashboard=lazy(()=>import('./pages/Dashboard'));const Pipeline=lazy(()=>import('./pages/Pipeline'));const Health=lazy(()=>import('./pages/Health'));const Forms=lazy(()=>import('./pages/Forms'));const FormDetail=lazy(()=>import('./pages/FormDetail'));const Submissions=lazy(()=>import('./pages/Submissions'));const Integrations=lazy(()=>import('./pages/Integrations'));const Billing=lazy(()=>import('./pages/Billing'));const HowItWorks=lazy(()=>import('./pages/HowItWorks'));const Privacy=lazy(()=>import('./pages/Privacy'));const Terms=lazy(()=>import('./pages/Terms'));const About=lazy(()=>import('./pages/About'));const Auth=lazy(()=>import('./pages/Auth'));
function Loading(){return <div className="splash"><div className="logoMark">F</div><b>WyForm</b><span>Loading…</span></div>}
function NotFound(){return <div className="card empty"><h2>Page not found</h2><p className="muted">That page does not exist.</p></div>}
export default function App(){const [user,setUser]=useState(undefined);const loc=useLocation();useEffect(()=>onAuthStateChanged(auth,setUser),[]);if(user===undefined)return <Loading/>;const publicPaths=['/privacy','/terms','/about','/how-it-works'];if(!user)return <Suspense fallback={<Loading/>}><Routes>{publicPaths.map(p=><Route key={p} path={p} element={p==='/privacy'?<Privacy/>:p==='/terms'?<Terms/>:p==='/about'?<About/>:<HowItWorks/>}/>)}<Route path="*" element={<Auth/>}/></Routes></Suspense>;return <Layout user={user}><Suspense fallback={<Loading/>}><Routes><Route path="/" element={<Dashboard user={user}/>}/><Route path="/forms" element={<Forms user={user}/>}/><Route path="/pipeline" element={<Pipeline user={user}/>}/><Route path="/health" element={<Health user={user}/>}/><Route path="/forms/:id" element={<FormDetail/>}/><Route path="/submissions" element={<Submissions user={user}/>}/><Route path="/integrations" element={<Integrations user={user}/>}/><Route path="/billing" element={<Billing user={user}/>}/><Route path="/how-it-works" element={<HowItWorks/>}/><Route path="/privacy" element={<Privacy/>}/><Route path="/terms" element={<Terms/>}/><Route path="/about" element={<About/>}/><Route path="*" element={<NotFound/>}/></Routes></Suspense></Layout>}
